name = "Rusty Poison"
license = "GPL-3.0 License"
licenselink = "https://github.com/RustyDaemon/rusty-poison/blob/master/LICENSE.md"
description = "A modern Hugo theme for dev bloggers."
min_version = "0.158.0"
version = "0.3.0"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/RustyDaemon/rusty-poison"

tags = ["blog", "personal", "dark", "dark-mode", "light", "modern"]
features = ["blog", "table-of-contents", "dark-mode", "series"]

[author]
    name = "Rusty Daemon"
    homepage = "https://github.com/RustyDaemon"
